import './globals.css';
import type { Metadata } from 'next';

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import QueryProvider from '@/Components/QueryProvider';
import AuthProvider from '@/Components/AuthProvider';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <QueryProvider>
        <html lang="en">
          <body className="overflow-x-hidden">
            <Navbar />
            {children}
            <Footer />
            <ToastContainer
              position="bottom-right"
              theme="dark"
              autoClose={3000}
            />
          </body>
        </html>
      </QueryProvider>
    </AuthProvider>
  );
}
